# Generated by Django 3.2.3 on 2021-05-25 09:34

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_price'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='product',
            managers=[
                ('prods', django.db.models.manager.Manager()),
            ],
        ),
    ]
